contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #alignercompare channel"
    url: https://nfcore.slack.com/channels/alignercompare
    about: Discussion about the nf-core/alignercompare pipeline
